### ISSUE TITLE
create-react-app has been deprecated for almost 2 years now.

### ISSUE THREAD

**Issue by TasseDeCafe** [openai/openai-realtime-console#1]
Use [Vite](https://vitejs.dev/) instead.

**Comment by TasseDeCafe** [comment]
@hourianto interestingly 4o indeed recommends using CRA: https://chatgpt.com/share/66fc4918-9f70-800a-8ec8-d0d62856d96d

That's pretty funny.

**Comment by JClackett** [comment]
dammmm, at least just use vite

**Comment by khorwood-openai** [comment]
Hey folks; appreciate the feedback. Going to close for now but not opposed to switching to Vite in the future! We have some Vite experts here (not me, unfortunately) that would probably agree with y'all but since it's non-blocking will close for now. :)
