### ISSUE TITLE
Error: Unexpected server response: 403 - (API not released yet?)

### ISSUE THREAD

**Issue by RedoxOwn** [openai/openai-realtime-console#10]
I tried to test the new realtime API with all the available methods, but I encountered the following errors:
![11](https://github.com/user-attachments/assets/6b784793-4a9c-4e09-8afe-18b843a90d88)
![22](https://github.com/user-attachments/assets/3acf0046-1694-40eb-b951-8dd0e6a6ab8b)
![33](https://github.com/user-attachments/assets/4141b1aa-77fd-4138-8c4b-079f1a91a2e1)
Could the issue simply be that the API key permissions haven't been rolled out yet?

**Comment by swiftdevv** [comment]
Yep theyre having connectivity issues rn.
