### ISSUE TITLE
Should this be returned, or "this"?

### ISSUE THREAD

**Issue by jonschlinkert** [openai/openai-realtime-console#11]
Looks like this was supposed to be returned https://github.com/openai/openai-realtime-console/blob/977a1d658efee57c36cc7344a58eda4f060d640c/src/lib/realtime-api-beta/lib/event_handler.js#L42

**Comment by khorwood-openai** [comment]
Thanks! I fixed this here: https://github.com/openai/openai-realtime-api-beta/commit/37fefd76b66624aeb828865f2fc9e3204b2b11e0

And I've now updated this repository to depend on the Realtime Client library directly.
