### ISSUE TITLE
Could not connect to "wss://api.openai.com/v1/realtime"

### ISSUE THREAD

**Issue by daishuge** [openai/openai-realtime-console#12]
Uncaught runtime errors:
×
ERROR
Could not connect to "wss://api.openai.com/v1/realtime"
    at WebSocket.connectionErrorHandler (http://localhost:3000/static/js/bundle.js:57849:18)

**Comment by dqnamo** [comment]
looks like not everybody has access yet https://github.com/openai/openai-realtime-console/issues/4

**Comment by daishuge** [comment]
> looks like not everybody has access yet https://github.com/openai/openai-realtime-console/issues/4

Hi there!
When i login in on
 https://platform.openai.com/playground/realtime

It give me this:

Personal does not have access to the Realtime API.

I think this is the reason

**Comment by khorwood-openai** [comment]
Closing as duplicate of https://github.com/openai/openai-realtime-console/issues/4
