### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND] running "npm run relay"

### ISSUE THREAD

**Issue by jambudipa** [openai/openai-realtime-console#14]
I can barely comprehend a company such as OpenAI publishing a repo like this for a flagship product feature that does not work out of the box.
```
import { RealtimeRelay } from './lib/relay.js';
```
...causes a module import error.

**Comment by khorwood-openai** [comment]
My fault! Broke this a little over an hour ago with: https://github.com/openai/openai-realtime-console/commit/7c5a173e10e595849d00c5e7f5db41a3fe5c8704

Fixed with: https://github.com/openai/openai-realtime-console/commit/851eb3165f47d44a534a4575d53a503e425477a5

Thanks for flagging!
