### ISSUE TITLE
Host a demo instance

### ISSUE THREAD

**Issue by fulldecent** [openai/openai-realtime-console#15]
Can you please host a demo instance? This will allow us to quickly evaluate this API and see if it is worth building on.

**Comment by khorwood-openai** [comment]
Hey there! As we roll out the Realtime API, when you have access you'll be able to play with it directly here:
https://platform.openai.com/playground/realtime

**Comment by AriesAlex** [comment]
I have forked the repository and set up GitHub Pages. The online instance is available at: https://ariesalex.github.io/openai-realtime-console
fork repo: https://github.com/AriesAlex/openai-realtime-console

**Comment by fulldecent** [comment]
Cool thank you
