### ISSUE TITLE
Relay Server doesn't proxy connection errors properly

### ISSUE THREAD

**Issue by Stevenic** [openai/openai-realtime-console#17]
When using the relay server there's an issue that the connection to the relay server doesn't properly proxy connection errors to OpenAI.  The relay server's socket always connects and there's no great way to signal that the proxy couldn't connect to OpenAI.  It just simply closes the connection.

You could send the error as an event and handle it via a "sever.error" event but it looks like the better approach might be to establish the connection to OpenAI from the "upgrade" event and not the "connection" event.  This is basically where they recommend you verify client credentials as it lets you accept or reject the client handshake. Moving the connect to "upgrade" should let you remove the message queue as well because the client won't be able to send any messages until after the connection to OpenAI is established. .

**Comment by Stevenic** [comment]
The current behavior is fine for testing and if I get some cycles I can take a crack at re-working the relay server.

**Comment by khorwood-openai** [comment]
Thanks for feedback! Closing for now as resolved; the Realtime API is also accessible to all Tier 1+ users at this point so we shouldn't see these failures as frequently.
