### ISSUE TITLE
[cloudflare/openai hackathon] still unable to access realtime api due to being in Tier 1

### ISSUE THREAD

**Issue by dankolesnikov** [openai/openai-realtime-console#18]
@kwhinnery, I've submitted the form (nerds@withshepherd.com), but still seeing Tier 1 in Billing page. 
Can you please help get us on Tier 4 account? 

Currently getting errors when connect in the app.

**Comment by codearranger** [comment]
@dankolesnikov I'm tier 4 and I don't have access to it.

**Comment by Stevenic** [comment]
I'm Tier 5 and don't have access. I actually don't know anyone who does but I'm sure they exist.

**Comment by dankolesnikov** [comment]
@OpenAIDevs PTAL

**Comment by khorwood-openai** [comment]
Closing as Realtime API should now be available to all users!
