### ISSUE TITLE
Getting a 404 when initializing the project

### ISSUE THREAD

**Issue by rpiacquadioryz** [openai/openai-realtime-console#23]
I'm getting an error when initializing the repo.

Following the steps in the README.md:
- "npm i"
- "npm start"

My node version is: v.20.15.0

Any idea what could be wrong?
Thanks.
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/fd5026aa-70c2-42e6-8b04-9ae78885ea91">

**Comment by khorwood-openai** [comment]
Any chance you're running a separate server that's hogging localhost:3000?

**Comment by romanpiacquadio** [comment]
Thanks for replying. No, it wasn't the port. It was NodeJS version, it wasn't working with v20 and v18 so I had to downgrade to v16 which worked.

**Comment by khorwood-openai** [comment]
Alright glad you got it working!
