### ISSUE TITLE
Hardware requirements for installation?

### ISSUE THREAD

**Issue by cjccjj** [openai/openai-realtime-console#41]
Hi, I attempted to install this on a VPS with 1GB of RAM, but the process failed during npm install, likely out of mem. Could you please advise on the minimum hardware requirements needed to successfully install and run this, for testing purposes? Thank you!

**Comment by khorwood-openai** [comment]
Can you give me steps to reproduce / exact errors you're encountering?

**Comment by cjccjj** [comment]
> Can you give me steps to reproduce / exact errors you're encountering?

Thank you for your reply.

With 1GB RAM, npm install failed after about 10 minutes, with the system log indicating it was killed due to an out-of-memory error. After upgrading to 2GB RAM, the installation completed successfully within minutes.
