### ISSUE TITLE
How to set prompt

### ISSUE THREAD

**Issue by 136William136** [openai/openai-realtime-console#43]
Hello. I just wonder anyone know how to set a system prompt in this console for demo?

**Comment by dmytro-tutorpeers** [comment]
All session-related updates, including setting instructions, must be consolidated inside the existing useEffect hook responsible for setting up the RealtimeClient.

Then, you must source the instructions from conversation_config.js (imported as defaultInstructions) and set within the useEffect hook.

Then edit the instructions file ../utils/conversation_config.js and write your own instructions

**Comment by topega** [comment]
All session-related updates, including setting instructions, must be consolidated inside the existing useEffect hook responsible for setting up the RealtimeClient.

Then, you must source the instructions from conversation_config.js (imported as defaultInstructions) and set within the useEffect hook.

Then edit the instructions file ../utils/conversation_config.js and write your own instructions

**Comment by khorwood-openai** [comment]
Marking as resolved, thanks @topega!

**Comment by jiaohu** [comment]
Sorry, the file ../utils/conversation_config.js is only on the branch  `websockets` , I want to use branch `main`. How could I set system prompt?
