### ISSUE TITLE
Consider publishing wavtools as a standalone library

### ISSUE THREAD

**Issue by arnaudbreton** [openai/openai-realtime-console#466]
Hi,

First of all, I want to thank you for developing the wavtools. I've struggled many hours to make something work with React Native + Expo and outdated libraries and your library just worked OOTB!

I was wondering if you could considering publishing it on its one? Currently I'm using it in a side project of mine, and I had to copy the code into it, which I think isn't a good approach. Or maybe I missed another nice way to do so?

Thanks

**Comment by davekiss** [comment]
Agree, feels like a great standalone library. Until then, you can add the GitHub repo as a dependency to your project within `package.json` and import it from there:

```json
    "dependencies": {
        "@openai/realtime-api-beta": "github:openai/openai-realtime-api-beta"
    }
```

Then, in your component:

```js
 import {
    WavRecorder,
    WavStreamPlayer,
} from "@openai/realtime-console/src/lib/wavtools/index.js";
```

**Comment by keithwhor** [comment]
Hey folks -- I'm no longer at OpenAI, so I went ahead and published this as a standalone library:

https://github.com/keithwhor/wavetools
https://www.npmjs.com/package/wavetools

Unfortunately somebody else (well-intentioned!) published under the `wavtools` namespace. I've reached out to see if I can nameswap back. For now you can `npm i wavetools --save` -- feel free to contribute there, and I'll do my best to keep it up to date. I'm using it, too!

**Comment by arnaudbreton** [comment]
Great stuff, thanks @keithwhor ! 

Thanks for the tip @davekiss
