### ISSUE TITLE
Azure OpenAI compatibility

### ISSUE THREAD

**Issue by vbandi** [openai/openai-realtime-console#9]
It would be awesome to have this running on Azure OpenAI as well.

**Comment by khorwood-openai** [comment]
Hey there! Will flag the request, but since it's out of scope of this repo, closing this issue. Thanks for the feedback!

**Comment by MSDNAndi** [comment]
Not a helpful response considering the collaboration between OpenAI and Microsoft.
Especially considering, that's just getting the URL and Headers right. It wouldn't make sense for Microsoft to need to create a fork of the whole repot just to add Azure OpenAI support (that would be wasteful).

**Comment by themass** [comment]
I also face the same problem

**Comment by cesarzeacelestial** [comment]
Same here.
